# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='staff_or_intern',
            field=models.IntegerField(choices=[(0, 'Neither'), (1, 'Staff'), (2, 'Intern')], default=0, verbose_name='Is staff or intern?'),
        ),
    ]
