# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170405_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_as_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_intern',
            field=models.BooleanField(default=False),
        ),
    ]
