# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170406_0201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='display_as_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_intern',
        ),
        migrations.AddField(
            model_name='user',
            name='staff_or_intern',
            field=models.IntegerField(choices=[(0, 'not_displayed'), (1, 'Estudio Caribe Staff'), (2, 'Estudio Caribe Intern')], default=0, verbose_name='Is staff or intern?'),
        ),
    ]
