# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170418_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='staff_or_intern',
            field=models.IntegerField(choices=[(0, 'Neither'), (1, 'Staff'), (2, 'Intern'), (3, 'Both')], default=0, verbose_name='Is staff, intern or both?'),
        ),
    ]
