# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170406_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='staff_or_intern',
            field=models.IntegerField(choices=[(0, 'Neither'), (1, 'Estudio Caribe Staff'), (2, 'Estudio Caribe Intern')], default=0, verbose_name='Is staff or intern?'),
        ),
    ]
