# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='date_released',
        ),
        migrations.AddField(
            model_name='work',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='work',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pressrelease',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='work',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='work',
            name='program',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='work',
            name='team',
            field=models.TextField(blank=True, default=''),
        ),
    ]
