# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_auto_20170411_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='publication',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='work',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
