# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_auto_20170415_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressrelease',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='publication',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='publication',
            name='medium',
            field=models.IntegerField(blank=True, choices=[(0, 'Article'), (1, 'Review'), (2, 'Book'), (3, 'Blogpost')], default=0),
        ),
        migrations.AlterField(
            model_name='work',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='work',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Planned'), (1, 'Under Construction'), (2, 'Completed')], default=0),
        ),
    ]
