# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import publications.models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0009_auto_20170419_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(default='', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=publications.models.work_directory_path)),
                ('caption', models.TextField(blank=True)),
                ('work', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cover', to='publications.Work')),
            ],
        ),
        migrations.RemoveField(
            model_name='workpicture',
            name='is_cover',
        ),
    ]
