# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import publications.models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0014_auto_20170512_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='press',
            name='press_kit',
            field=models.FileField(blank=True, null=True, upload_to=publications.models.press_directory_path),
        ),
    ]
