# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import home_images.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('slug', models.SlugField(blank=True, default='', max_length=100)),
                ('image', models.ImageField(null=True, upload_to=home_images.models.home_image_directory_path)),
                ('caption', models.TextField(blank=True)),
                ('order', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
