# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_images', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeimage',
            options={'ordering': ('order',), 'verbose_name': 'home image', 'verbose_name_plural': 'home images'},
        ),
        migrations.AlterField(
            model_name='homeimage',
            name='order',
            field=models.IntegerField(default=0, help_text='If 0, image will not be displayed'),
        ),
        migrations.AlterField(
            model_name='homeimage',
            name='title',
            field=models.CharField(blank=True, default='-', max_length=100),
        ),
    ]
