# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 10:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_images', '0002_auto_20170502_2152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeimage',
            options={'ordering': ('order', 'title'), 'verbose_name': 'home image', 'verbose_name_plural': 'home images'},
        ),
    ]
