# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_images', '0003_auto_20170509_0612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeimage',
            options={'ordering': ('display_order', 'title'), 'verbose_name': 'home image', 'verbose_name_plural': 'home images'},
        ),
        migrations.RenameField(
            model_name='homeimage',
            old_name='order',
            new_name='display_order',
        ),
        migrations.AddField(
            model_name='homeimage',
            name='parallax',
            field=models.BooleanField(default=False),
        ),
    ]
